### ISSUE TITLE
[TypeError: Cannot read property '0' of null]

### ISSUE THREAD

**Issue by marcomb** [zazukoians/schemaorg-geocoder#2]
I sorted out the geocoding provider (a matter of quotes) and I am using google right now.

I run this command:
curl -X POST -H "Content-type: text/turtle" -H "Accept: tele" --data-binary "@test/shops.ttl" http://localhost:8080/geocoder
curl: (52) Empty reply from server

I get this output, please note that is parsing the file (outputting the address) but I get final error (type error) and no geocoding in.

C:\Users\IT487\Documents\GitHub\schemaorg-geoc
ex.js
restify listening at http://[::]:8080
Via Chimelli 18, 38057, Pergine Valsugana
Piazza Cal Di Ponte 15, 38065, Mori
Corso Ausugum 32, 38051, Borgo Valsugana
Via De Gasperi 2, 38017, Mezzolombardo
Piazza Marconi 1, 38053, Castello Tesino
Piazza Municipio  2, 38052, Caldonazzo
Via delle Villa 37, 38052, Caldonazzo
Via Strada Nuova  8, 38064, Folgaria
Via A. Maffei 52, 38064, Folgaria
[TypeError: Cannot read property '0' of null]

**Comment by ktk** [comment]
@marcomb can you checkout the latest git version and try again? This should log some details with the error

**Comment by ktk** [comment]
ah something else, your query is wrong, can you delete the `-H "Accept: tele"`

**Comment by ktk** [comment]
To be precise, the correct query should be this:

```
curl -X POST -H "Content-type: text/turtle" -H "Accept: text/turtle" --data-binary "@test/shops.ttl" http://localhost:8080/geocoder  
```

**Comment by marcomb** [comment]
I update the version with the logging, now I have this log. Seems to be a problem in exiting the forEach loop

TypeError: Cannot read property '0' of null
    at C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\index.js:132:69
    at Array.forEach (native)
    at C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\index.js:114:21
    at _fulfilled (C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\IT487\Documents\GitHub\schemaor
g-geocoder\node_modules\q\q.js:796:13)
    at C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\node_modules\q\q.js:604:44
    at runSingle (C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\node_modules\q\q.js:137:13)
    at flush (C:\Users\IT487\Documents\GitHub\schemaorg-geocoder\node_modules\q\q.js:125:13)
    at nextTickCallbackWith0Args (node.js:456:9)

**Comment by ktk** [comment]
@marcomb from the code it looks like there is no geocoding happening, so my only guess is that either your API key does not work or something else goes wrong (not sure if node-geocoder was tested on windows). I should probably add some test to the code that it reports an empty result from geocoder instead of failing on the forEach.

On the other hand geocoder also does not seem to send back an error, at least I would expect that I would go into the catch() in my code in case there is one.

**Comment by marcomb** [comment]
Could be an issue with BATCHGEOCODE?I installed just running the command "npm batchgeocode". DO I have to do more?

Marco Combetto
marcomb@hotmail.com
Mobile: +39 3316329971
www.linkedin.com/in/marcomb 

Date: Thu, 28 Jan 2016 02:40:05 -0800
